version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: parloa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - parloa_network

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: parloa_redisinsight
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - parloa_network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  backend:
    build:
      context: .
    container_name: parloa_backend
    working_dir: /app
    command: /bin/sh -c "npm install && npm run start:dev"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_TTL_SECONDS: 3600
      GITHUB_RANKING_BASE_URL: https://raw.githubusercontent.com/EvanLi/Github-Ranking/master/Data
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    networks:
      - parloa_network

networks:
  parloa_network:
    driver: bridge
