version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - parloa_network

  backend:
    build:
      context: .
    container_name: parloa_backend
    working_dir: /app
    command: /bin/sh -c "npm install && npm run start:dev"
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      CACHE_TTL_SECONDS: 3600
      GITHUB_RANKING_BASE_URL: https://raw.githubusercontent.com/EvanLi/Github-Ranking/master/Data
      PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - redis-stack
    volumes:
      - ./backend:/app
    networks:
      - parloa_network

networks:
  parloa_network:
    driver: bridge
