version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: parloa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - parloa_network

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: parloa_redisinsight
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - parloa_network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


networks:
  parloa_network:
    driver: bridge
