export enum LanguageEnum {
  TypeScript = 'TypeScript',
  Python = 'Python',
  JavaScript = 'JavaScript',
  Cpp = 'C++',
  Java = 'Java',
  Shell = 'Shell',
  HTML = 'HTML',
  Go = 'Go',
  Rust = 'Rust',
  PHP = 'PHP',
  Clojure = 'Clojure',
  Batchfile = 'Batchfile',
  JupyterNotebook = 'Jupyter Notebook',
  Markdown = 'Markdown',
  Dockerfile = 'Dockerfile',
  R = 'R',
  Groovy = 'Groovy',
  VimScript = 'Vim Script',
  CSS = 'CSS',
  Vue = 'Vue',
}
